#!/bin/bash
if [ "$1" == "--uninstall" ]; then
  # Uninstall steps copied from http://therealmarv.com/blog/how-to-fully-uninstall-the-offical-docker-os-x-installation/

  # First stop boot2docker and delete the VBox image:
  if type "boot2docker" &> /dev/null; then
    boot2docker stop
    boot2docker delete
  fi

  # Remove Docker and boot2docker command line tools:
  sudo rm /usr/local/bin/docker
  sudo rm /usr/local/bin/boot2docker

  # Remove boot2docker VBox image:
  sudo rm /usr/local/share/boot2docker/boot2docker.iso
  sudo rmdir /usr/local/share/boot2docker

  rm -rf ~/.boot2docker

  # Remove boot2docker ssh keys:
  rm ~/.ssh/id_boot2docker*

  # Remove additional boot2docker files in /private folder:
  sudo rm -f /private/var/db/receipts/io.boot2docker.*
  sudo rm -f /private/var/db/receipts/io.boot2dockeriso.*

  # Uninstall VirtualBox with tool from VirtualBox dmg
  ./VirtualBox_Uninstall.tool
else
  VERSION=$(curl -s https://github.com/boot2docker/osx-installer/releases/latest | sed -En 's/.*v([0-9.]+).*/\1/p')
  curl -LO https://github.com/boot2docker/osx-installer/releases/download/v$VERSION/Boot2Docker-$VERSION.pkg
  sudo installer -pkg Boot2Docker-$VERSION.pkg -target /
  boot2docker init

  echo "Boot2Docker installed. Test with:"
  echo "boot2docker up ; \$(boot2docker shellinit) ; docker run hello-world"
fi